spring:
  datasource:
    url: jdbc:mysql://localhost:3306/somos_mas?serverTimezone=UTC
    username: root
    password: UNgs#1409
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
      
amazonProperties:
  endpointUrl: https://s3.us-east-1.amazonaws.com
  accessKey: AKIA5YX3QC3YARN66KVE
  secretKey: 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
  bucketName: alkemy-somos-mas


  # Security
  # jwt.secret=
  # jwt.expiration=36000