spring:
  datasource:
    url: jdbc:mysql://localhost:3306/somos_mas?serverTimezone=UTC
    username: root
    password: 123456
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  # Security
  # jwt.secret=
  # jwt.expiration=36000

app:
  sengrid:
    key: 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
    templateId: d-769bb1b4886846489e62142f0b6f7226