spring:
  datasource:
    url: jdbc:mysql://localhost:3306/somos_mas?serverTimezone=UTC
    username: user
    password: password
    driver-class: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  security:
    jwt:
      secret-key: secret-key
      expiration-length: 3600000