spring:
  datasource:
    url: jdbc:mysql://localhost:3306/somos_mas?serverTimezone=UTC
    username: user
    password: password
    driver-class: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    jwt:
      secret-key: secret-key
      expiration-length: 3600000
      
amazonProperties:
    endpointUrl: https://s3.us-east-1.amazonaws.com
    accessKey: AKIA5YX3QC3YARN66KVE
    secretKey: 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
    bucketName: alkemy-somos-mas
    
    #endpointUrl: https://s3.us-east-3.amazonaws.com
    #accessKey: AKIA5YX3QC3YARN66KVl
    #secretKey: IgkUka/GWx/wMn6Py6CSoc13UKA+OxTJQjPX8r+1
    #bucketName: alkemy-somos

app:
  sengrid:
    key: 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
    emailIssuing: matias-leandro@outlook.com


