spring:
  datasource:
    url: jdbc:mysql://localhost:3306/somos_mas?serverTimezone=UTC
    username: root
    password:
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  # Security
  # jwt.secret=
  # jwt.expiration=36000